window:
  width: 800
  height: 600

dungeon:
  width: 30
  height: 30

random:
  seed: 8ae8865c461f77fd321851c830f8bbeb49df254d
  useFixedSeed: false

camera:
  zoom: 1.0
  origin: -3000
  width: 5000
  speed: 2.0
