window:
  width: 2000
  height: 1000

dungeon:
  width: 40
  height: 40
  rooms: 20

random:
  seed: 8ae8865c461f77fd321851c830f8bbeb49df254d
  useFixedSeed: true


camera:
  zoom: 0.4
  origin: -3000
  width: 7000
  speed: 2.0
