window:
  width: 800
  height: 800

dungeon:
  width: 100
  height: 100
  rooms: 50

random:
  seed: 8ae8865c461f77fd321851c830f8bbeb49df254d
  useFixedSeed: true


camera:
  zoom: 0.4
  origin: -10000
  width: 20000
  speed: 3.0
