window:
  width: 800
  height: 600

dungeon:
  width: 30
  height: 30

random:
  seed: 8ae8865c461f77fd321851c830f
  useFixedSeed: false

camera:
  zoom: 0.4
  origin: -2000
  width: 4000
  speed: 2.0
