assets:
  walls:
    - stoneWall
    - stoneWallAged
    - stoneWallStructure
    - stoneWallWindow
    - stoneWallWindowbars
    - stoneWallHalf
    - stoneWallGate
    - stoneWallGateBars
    - stoneWallGateClosed
    - stoneWallGateOpen

  walls_end:
    - stoneWallBroken

  floors:
    - dirt
    - stoneTile
    - stoneUneven
    - dirtTiles
    - stone

  objects:
    - barrel
    - barrels
    - barrelsStacked
    - chair
    - tableChairsBroken
    - tableRound
    - stairs
    - stairsAged
    - stairsSpiral
    - planks
    - bridge
    - bridgeBroken

  stairs:
    - stairs
    - stairsAged
