#pragma once
#include <GLFW/glfw3.h>
#include <string>
#include <vector>
#include <memory>
#include <cstdlib>
#include <cstdio>
#include "format.hpp"
#include "error_utils.hpp"
#include "../config.hpp"
